# Generated by Django 6.0.4 on 2026-05-13 18:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#14383F', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flowchart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowcharts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('shape', models.CharField(choices=[('process', 'Process'), ('start', 'Start / End'), ('decision', 'Decision'), ('io', 'Input / Output'), ('data', 'Data'), ('note', 'Note')], default='process', max_length=20)),
                ('branch_label', models.CharField(blank=True, help_text='Optional label shown on the line from the parent (e.g. "Yes", "No").', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, help_text='Optional override. Leave blank to use the shape default color.', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flowchart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='main_app.flowchart')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main_app.node')),
                ('tags', models.ManyToManyField(blank=True, related_name='nodes', to='main_app.tag')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='main_app.node')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
