# Generated by Django 6.0.4 on 2026-05-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional second line rendered as small italic text under the label.', max_length=160),
        ),
        migrations.AddField(
            model_name='node',
            name='x_pos',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='y_pos',
            field=models.FloatField(default=0),
        ),
    ]
