# Generated by Django 6.0.4 on 2026-05-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_flowchartshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional attached image — useful for screenshots of sub-flows, wireframes, or reference diagrams.', null=True, upload_to='node_images/%Y/%m/'),
        ),
    ]
