# Generated by Django 6.0.4 on 2026-05-14 22:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_node_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(help_text='The full document text. Paste your NDA / agreement here. Line breaks preserved.')),
                ('status', models.CharField(choices=[('draft', 'Draft — not shareable yet'), ('open', 'Open for signing'), ('closed', 'Closed — no further signatures')], default='draft', max_length=10)),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flowchart', models.ForeignKey(blank=True, help_text='Optional: link this document to a flowchart so collaborators see it in context.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='main_app.flowchart')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(help_text='The full legal name the signer typed.', max_length=160)),
                ('signer_email', models.EmailField(blank=True, max_length=254)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=320)),
                ('typed_signature', models.CharField(max_length=160)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='main_app.document')),
            ],
            options={
                'ordering': ['signed_at'],
            },
        ),
    ]
