# Generated by Django 6.0.4 on 2026-05-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_flowchartinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='disclosing_party_name',
            field=models.CharField(blank=True, help_text='Your full legal name as the Disclosing Party. Auto-populates the signature block on the generated PDF. Leave blank to use your account email.', max_length=160),
        ),
    ]
