# Generated by Django 6.0.4 on 2026-05-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_document_disclosing_party_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='body',
            field=models.TextField(help_text="The numbered clauses of the agreement. The Effective Date, Parties block, and Signatures section are generated automatically — don't paste those in."),
        ),
        migrations.AlterField(
            model_name='document',
            name='disclosing_party_name',
            field=models.CharField(blank=True, help_text='Your full legal name as the Disclosing Party. Populates the Parties preamble and the signature block on the generated PDF. Leave blank to use your account email.', max_length=160),
        ),
    ]
